version: "3.1"
  
services:
  node:
    image: node
    ports:
    - 5050:5050
    environment:
      MONGO_DB_USERNAME: admin
      MONGO_DB_PWD: qwerty
  mongo:
    image: mongo
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
  mongo-express:
    image: mongo-express
    ports:
    - 8081:8081
    environment:
    ME_CONFIG_MONGODB_ADMINUSERNAME: admin
    ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
    ME_CONFIG_MONGODB_URL: "mongodb://admin:qwerty@mongo:27017"

